


// metodo correcto para crear una empres
get  http://localhost:3001/tareas/dia/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODY0MzI2NTR9.emUnn3lH-AHYjPXe6Ncjg1WwhdPsAKAxSR7n45pFh3I

{
  "EmpleadoId": "1"
}



# POST  http://localhost:3001/empleados/

# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODY0MzI2NTR9.emUnn3lH-AHYjPXe6Ncjg1WwhdPsAKAxSR7n45pFh3I

# {
#   "nombre": "Bruno Veloso",
#   "telefono": 56972149853,
#   "apellidos": "Veloso",
#   "rut": "203028431",
#   "cargo": "Founder",
#   "profesion": "Creador de Videos",
#   "edad": 22,
#   "empresaId": 1
# }



# // metodo correcto para crear una empresa
# POST  http://localhost:3001/empresas/
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODY0MzI2NTR9.emUnn3lH-AHYjPXe6Ncjg1WwhdPsAKAxSR7n45pFh3I

# {
#   "nombre": "LIMBIK TECH",
#   "cantidad_empleados": 0,
#   "estado_suscripcion": true,
#   "rut": "1111111",
#   "prompt": "Eres un asistente virtual para ayudar a los empleados de le empresa Limbik Tech"
# }

# POST  http://localhost:3001/conversacion/
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODY0MzI2NTR9.emUnn3lH-AHYjPXe6Ncjg1WwhdPsAKAxSR7n45pFh3I

# {
#   "titulo": "Quien fue arturo prat",
#   "categoria": "historia de chile",
#   "total_tokens": 300,
#   "EmpleadoId": "1"
# }


# // metodo correcto para crear una empresa
# POST  http://localhost:3001/empresas/
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODY0MzI2NTR9.emUnn3lH-AHYjPXe6Ncjg1WwhdPsAKAxSR7n45pFh3I

# {
#   "nombre": "LIMBIK TECH",
#   "cantidad_empleados": 0,
#   "estado_suscripcion": true,
#   "rut": "1111111",
#   "prompt": "Eres un asistente virtual para ayudar a los empleados de le empresa Limbik Tech"
# }


